@startuml "usecaseglobaltotal"

skinparam actorStyle Hollow 

:User: as user

(gestion des services) as (servicemanaging)

(imaginary) as (imaginary)

(Authentification) as (authentification)

(Redimension de fichier) as (resizeImaginary)
(Convertion de fichier) as (convertImaginary)

user -- (servicemanaging)

(imaginary) -- (authentification)

(servicemanaging) -- (imaginary)

(authentification) <.. (resizeImaginary)
(authentification) <.. (convertImaginary)

@enduml